export const GET_MOVIES_START = 'GET_MOVIES_START';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL';
export const GET_MOVIES_CLEANUP = 'GET_MOVIES_CLEANUP';

export const GET_MOVIE_BYID_START = 'GET_MOVIE_BYID_START';
export const GET_MOVIE_BYID_SUCCESS = 'GET_MOVIE_BYID_SUCCESS';
export const GET_MOVIE_BYID_FAIL = 'GET_MOVIE_BYID_FAIL';
export const GET_MOVIE_BYID_CLEANUP = 'GET_MOVIE_BYID_CLEANUP';

export const RATE_MOVIE_START = 'RATE_MOVIE_START';
export const RATE_MOVIE_SUCCESS = 'RATE_MOVIE_SUCCESS';
export const RATE_MOVIE_FAIL = 'RATE_MOVIE_FAIL';
export const RATE_MOVIE_CLEANUP = 'RATE_MOVIE_CLEANUP';
